# Generated by Django 6.0.6 on 2026-06-07 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('building', models.CharField(blank=True, default='', max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FloorObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=40)),
                ('label', models.CharField(blank=True, default='', max_length=160)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
                ('rotation', models.FloatField(default=0)),
                ('zone', models.CharField(blank=True, default='Common Area', max_length=80)),
                ('is_bookable', models.BooleanField(default=False)),
                ('layer_group', models.CharField(blank=True, default='', max_length=40)),
                ('is_visible', models.BooleanField(default=True)),
                ('custom_color', models.CharField(blank=True, default='', max_length=20)),
                ('image_src', models.CharField(blank=True, default='', max_length=300)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='floors.floor')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['floor', 'is_bookable'], name='floors_floo_floor_i_21db6c_idx')],
            },
        ),
    ]
