# Generated by Django 6.0.6 on 2026-06-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40, unique=True)),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
            ],
        ),
    ]
